feat: add support for gpt4o
hupe1980/go-tiktoken pull request #1
Opened 2024-05-14 23:21 UTC by matthiasthomas

📜 Lore

Adding support to gpt4o which came out yesterday May, 13th 2024.

🗝️ Key Changes

🛡️ Main Quests

[x] Add support for gpt4o

2024-05-14 23:21 UTC, matthiasthomas commented
@hupe1980 - Would you mind approving this one 🙏 It would unblock me

2024-05-17 18:18 UTC, hupe1980 requested changes

2024-05-17 18:18 UTC, hupe1980 commented on tiktoken.go
> +	"gpt-4o-":        CL100kBase, // e.g., gpt-4o-2024-05-13, etc.
Shouldn't it actually be o200k?

2024-05-17 18:18 UTC, hupe1980 commented on tiktoken.go
> +	"gpt-4o":        CL100kBase,
Same here. o200k?

2024-05-17 19:29 UTC, matthiasthomas commented on tiktoken.go
> +	"gpt-4o-":        CL100kBase, // e.g., gpt-4o-2024-05-13, etc.
Totally @hupe1980 , sorry about that, didn't realize they changed the tokenizer. It's fixed, I've updated according to the latest from https://github.com/openai/tiktoken/tree/main

2024-05-18 05:45 UTC, hupe1980 approved these changes
LGTM! Thx

2024-05-18 05:45 UTC, merged